# Generated by Django 4.2.6 on 2023-10-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='image',
            field=models.ImageField(default=1, upload_to='bar/image'),
            preserve_default=False,
        ),
    ]
